name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: ["2.13.16", "3.7.2"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: 24=tgz+https://github.com/adoptium/temurin24-binaries/releases/download/jdk-24%2B36/OpenJDK24U-jdk_x64_linux_hotspot_24_36.tar.gz

      - name: Compile
        run: sbt "++${{ matrix.scala }} compile"

      - name: Run tests
        run: sbt "++${{ matrix.scala }} test"

      - name: Build assembly
        run: sbt "++${{ matrix.scala }} cli/assembly"
